### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by doniks** [ubports/ubports-app#10]
Team and getinvolved don't work. I think due to website redesign

**Comment by Fuchur777** [comment]
Should be fixed now

**Comment by Fuchur777** [comment]
These two urls are fixed

**Comment by doniks** [comment]
Team link still doesn't work for me:

- open openstore
- check that ubports-app is the most recent
-> 1.4, no updates available
- open ubports-app
- tap on burger top left
- tap on "Meet the team"
-> browser opens to https://ubports.com/team which gives a 404: Page not found

"Get Involved" DOES work now, but "Meet The Team" still DOES NOT work for me.

**Comment by Fuchur777** [comment]
Meet the team fixed as well.

However subscribe still links to the wrong page. Should be: http://ubports.com/r/subscribe instead of bit.ly
